[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "otto"
version = "0.0.1"
authors = [
  { name="Roy Larsen", email="roy.larsen@mobileheartbeat.com" },
]
description = "DevOps Automation Tool"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/mhroylarsen/otto"
"Bug Tracker" = "https://github.com/mhroylarsen/otto/issues"

[project.scripts]
otto = src:main